### ISSUE TITLE
Inconsistent GT location between the positive and semi-positive satellite images

### ISSUE THREAD

**Issue by TedLentsch** [Jeff-Zilence/VIGOR#2] opened 2022-03-09 14:40 UTC
I have downloaded the VIGOR dataset (link obtained via authors) and created a [Jupyter Notebook](https://github.com/TedDeVriesLentsch/Street-to-Satellite_Image_Matching/blob/main/VisualizeGeometricPrior_VIGOR_GitHub_Issue.ipynb) to visualize the data. Each street image has 1 positive satellite image and 3 semi-positive satellite images (details about positive and semi-positives are in the VIGOR paper). I see inconsistency between the ground truth location of different satellite images for Seattle, while I do not see this for New York, for example. Therefore, I suspect that there is something wrong with Seattle's labels (and possibly those of other cities as well).

Below is a screenshot from my Jupyter Notebook for street image --Bm25YXcr-aJ-Nbdz0oIw,47.593046,-122.300124,.jpg of Seattle. It can be seen that the yellow dot (the ground truth location) is on the right side of the road for the positive and semi-positive 2 satellite image, while for semi-positives 1 and 3 it is on the left side of the road.

![image](https://user-images.githubusercontent.com/82224705/157459579-5e9f4575-7ee0-4847-901e-91191e340f51.png)

Below is a screenshot from my Jupyter Notebook for street image -DO-hyYo-ICf5irvAKwMMw,40.717596,-73.975717,.jpg of New York. It can be seen that the location here is consistent between the different satellite images.

![image](https://user-images.githubusercontent.com/82224705/157460257-52295cfb-08c9-404f-a8b9-bcfe457130ba.png)

I would like to know if others can also reproduce this problem and how this possible problem could be solved.

**Comment by Jeff-Zilence** [comment] 2022-03-09 16:59
Thank you for your interest in this dataset. The raw GPS data of all the images is provided, so you can generate the offset by your own. The small drift in this example could be caused by the approximation in GPS_to_meter conversion. It is also possible that the satellite images have different resolution for different cities, so the pixel-level offset may not be very accurate even if the meter-level distance is accurate. The resolution was estimated in NewYork, and I think this could be the reason why NewYork is ok. This could be fixed if you can estimate the ground resolution of satellite images in these four cities. For example, you can select two objects in this figure and measure the meter-level distance in Google map:
![image](https://user-images.githubusercontent.com/46680018/157490450-d49a4739-c0e6-414f-8afa-3d348fedb135.png)
Then find these two points in the image you plotted with python, and compute how many pixels are there. You can get better resolution for each city and hopefully this can fix the issue. 
If you just wanna do meter-level evaluation in the paper, then this does not matter, because we compute the meter-level distance with raw GPS, not the pixel-level offset. Hope this answers your question.

**Comment by TedLentsch** [comment] 2022-03-09 20:48
Thanks for your quick reply. So the error may have two causes: (1) incorrect conversion from GPS to meters and (2) an incorrect spatial resolution value.

I applied your method for estimating the spatial resolution and these are my first results based on the two positive satellites images from my first post:

Seattle: 0.101 meter/pixel
New York: 0.113 meter/pixel
So that is a difference of 1.2 cm/pixel.

The distance between the location of the satellite image (positive) and the satellite image (semi-positive 3) of Seattle from my first post is about half the diagonal of the image, or about 450 pixels. This would amount to a difference of about 5 meters if I use the 1.2 cm/pixel, while the road is about 6 meters wide according to Google Earth. So I think it's possible that an incorrect value of the spatial resolution is causing the inconsistency between the locations.

**Comment by Jeff-Zilence** [comment] 2022-03-09 20:57
Thank you for verifying that the drift is caused by the resolution issue. By the way, I don't think there is anything "incorrect", the approximation could have little difference there. I will close the issue if there is no further question.

**Closed as completed** 2022-03-09 21:01 UTC

**Comment by Jeff-Zilence** [comment] 2022-03-09 21:12
Thank you for your effort on this. If you have measured the resolution of all the four cities, you may share your findings somewhere so that people can follow. I may re-compute the pixel-level offset in the future for this dataset.

**Comment by Miaowshroom** [comment] 2022-05-11 07:49
I am having one concern regarding this inconsistency:

1. For training, if he inconsistency presents in the dataset, will this naturally downgrade the achievable accuracy of the model? 

2. For testing, more fundamentally, if the resolutions across the dataset are different, how the predicted results are translated from pixel to meter? e.g. the function Lat_Lng use a default resolution 0.114 to calculate the shift of half image in degree unit. but the resolution (ground sampling distance) are different for different images.

**Comment by Jeff-Zilence** [comment] 2022-05-11 15:16
Thank you for your interest. 
1. This could downgrade the accuracy of the model, but one can use the above steps to recompute the resolutions to avoid this. Besides, every dataset has noise (e.g. ImageNet), and the resolution would not be perfect.
2. Current model predicts offset as a number in [0,1] which is the ratio compared with width,height of the image. This model uses Lat_Lng to translate from pixel to meter, which could be a limitation. But for other methods, it is not necessary to follow the same steps. One can directly predict the GPS using the model, then evaluate using gps2distance without Lat_Lng.
